package no.nav.yrkesskade.kodeverk.config

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.context.properties.ConfigurationPropertiesScan

@SpringBootConfiguration
@ConfigurationPropertiesScan
class ApplicationConfig