KODEVERK_CLIENT_ID: ${AZURE_APP_CLIENT_ID}
ENV: dev

spring:
  application.name: yrkesskade-kodeverk
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${YRKESSKADE_KODEVERK_DB_HOST}:${YRKESSKADE_KODEVERK_DB_PORT}/${YRKESSKADE_KODEVERK_DB_DATABASE}
    username: ${YRKESSKADE_KODEVERK_DB_USERNAME}
    password: ${YRKESSKADE_KODEVERK_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      connection-test-query: "select 1"
      max-lifetime: 30000
      minimum-idle: 1
      data-source-properties:
        stringtype: unspecified # Nødvendig for å kunde sende en String til et json-felt i PostgresSql

api:
  client:
    kodeverk:
      url: https://yrkesskade-proxy.dev-fss-pub.nais.io/kodeverk/
  whitelist:
    clients:
      - 12df7924-7eda-4f8a-bbd0-9be3081f9fea # saksbehandling frontend
      - a136534f-4a9f-40c8-b96d-49a4bcb07fc2 # saksbehandling backend

