spring:
  application.name: yrkesskade-kodeverk
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_kodeverk
    username: ${YRKESSKADE_KODEVERK_DB_USERNAME}
    password: ${YRKESSKADE_KODEVERK_DB_PASSWORD}


mock:
  enabled: true
  port: 10099

api:
  client:
    kodeverk:
      url: https://kodeverk.dev.intern.nav.no/
