CLUSTER: gcp
KODEVERK_CLIENT_ID: ${ENV}-${CLUSTER}.yrkesskade-kodeverk

spring:
  application.name: yrkesskade-kodeverk
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_kodeverk
  flyway:
    out-of-order: true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}

YRKESSKADE_PROXY_CLIENT_ID: dev-fss.yrkesskade.yrkesskade-proxy
no.nav.security.jwt:
  issuer:
    azuread:
      discoveryurl: ${AZURE_APP_WELL_KNOWN_URL}
      accepted_audience: ${KODEVERK_CLIENT_ID}
      cookie_name: azure_token
  client:
    registration:
      yrkesskade-proxy:
        token-endpoint-url: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
        grant-type: client_credentials
        scope: api://${YRKESSKADE_PROXY_CLIENT_ID}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt

api:
  client:
    kodeverk:
      url: https://kodeverk.dev.intern.nav.no/
