AZURE_APP_JWK: ./src/test/resources/jwks/jwk.json
AZURE_APP_CLIENT_ID: yrkesskade-kodeverk
AZURE_OPENID_CONFIG_TOKEN_ENDPOINT:  https://fakedings.dev-gcp.nais.io/aad/token
AZURE_APP_WELL_KNOWN_URL: https://fakedings.dev-gcp.nais.io/fake/.well-known/openid-configuration
ENV: local

spring:
  application.name: yrkesskade-kodeverk
  main:
    banner-mode: "off"
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/yrkesskade_kodeverk
    username: ${YRKESSKADE_KODEVERK_DB_USERNAME}
    password: ${YRKESSKADE_KODEVERK_DB_PASSWORD}

mock:
  enabled: true
  port: 10099

api:
  client:
    kodeverk:
      url: https://yrkesskade-proxy.dev.intern.nav.no/kodeverk/
  whitelist:
    clients:
